"""
SQLAlchemy database models for AI Study Assistant.
"""
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text, Boolean, Float, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from backend.database import Base
import enum
import json


class ChatMode(str, enum.Enum):
    """Chat mode: Free, Document, or Notes."""
    FREE = "free"
    DOCUMENT = "document"
    NOTES = "notes"


class User(Base):
    """User model for authentication."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(100), unique=True, index=True, nullable=False)
    email = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    documents = relationship("Document", back_populates="owner", cascade="all, delete-orphan")
    conversations = relationship(
        "Conversation", back_populates="user", cascade="all, delete-orphan"
    )
    exams = relationship("Exam", back_populates="user", cascade="all, delete-orphan")
    exam_attempts = relationship("ExamAttempt", back_populates="user", cascade="all, delete-orphan")
    user_achievements = relationship("UserAchievement", back_populates="user", cascade="all, delete-orphan")
    user_progress = relationship("UserProgress", back_populates="user", cascade="all, delete-orphan")
    study_plans = relationship("StudyPlan", back_populates="user", cascade="all, delete-orphan")
    topic_stats = relationship("UserTopicStats", back_populates="user", cascade="all, delete-orphan")
    group_memberships = relationship("GroupMembership", back_populates="user", cascade="all, delete-orphan")
    group_messages = relationship("GroupMessage", back_populates="user", foreign_keys="GroupMessage.user_id")
    message_votes = relationship("MessageVote", back_populates="user", cascade="all, delete-orphan")


class Document(Base):
    """Document model for storing uploaded PDFs metadata."""
    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    filename = Column(String(255), nullable=False)
    # Path on disk to extracted text / chunks (do not store raw text in MySQL)
    content_path = Column(String(500), nullable=True)
    # JSON string mapping page numbers to text chunks
    page_data_path = Column(String(500), nullable=True)  # Path to JSON file with page->text mapping
    total_pages = Column(Integer, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    owner = relationship("User", back_populates="documents")
    conversations = relationship(
        "Conversation", back_populates="document", foreign_keys="Conversation.document_id"
    )


class Conversation(Base):
    """Chat conversation."""
    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(255), nullable=False, default="New Chat")
    mode = Column(String(20), nullable=False, default=ChatMode.FREE.value)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    notes_context = Column(Text, nullable=True)  # Pasted text for Notes mode
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="conversations")
    document = relationship("Document", back_populates="conversations")
    messages = relationship(
        "Message", back_populates="conversation", cascade="all, delete-orphan"
    )


class Message(Base):
    """Individual chat message."""
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    conversation_id = Column(
        Integer, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False
    )
    role = Column(String(20), nullable=False)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    document_id = Column(
        Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    conversation = relationship("Conversation", back_populates="messages")


class StudyPlan(Base):
    """Study plan generated by AI."""
    __tablename__ = "study_plans"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(255), nullable=False)
    topic = Column(Text, nullable=False)
    plan_type = Column(String(20), nullable=False)  # "daily", "weekly", "monthly"
    content = Column(Text, nullable=False)  # Markdown content
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="study_plans")


class Exam(Base):
    """Exam/Quiz created from documents or notes."""
    __tablename__ = "exams"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(255), nullable=False)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    notes_context = Column(Text, nullable=True)
    questions_json = Column(Text, nullable=False)  # JSON array of questions
    time_limit_minutes = Column(Integer, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user = relationship("User", back_populates="exams")
    document = relationship("Document")
    attempts = relationship("ExamAttempt", back_populates="exam", cascade="all, delete-orphan")


class ExamAttempt(Base):
    """User's attempt at an exam."""
    __tablename__ = "exam_attempts"

    id = Column(Integer, primary_key=True, index=True)
    exam_id = Column(Integer, ForeignKey("exams.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    answers_json = Column(Text, nullable=False)  # JSON object: {question_id: answer}
    score = Column(Float, nullable=True)  # Percentage score
    time_taken_seconds = Column(Integer, nullable=True)
    completed = Column(Boolean, default=False)
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    exam = relationship("Exam", back_populates="attempts")
    user = relationship("User", back_populates="exam_attempts")


class Achievement(Base):
    """Achievement/Badge definition."""
    __tablename__ = "achievements"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(50), unique=True, nullable=False)  # e.g., "first_exam", "week_streak"
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    icon = Column(String(50), nullable=True)  # Icon class name
    points = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class UserAchievement(Base):
    """User's earned achievements."""
    __tablename__ = "user_achievements"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    achievement_id = Column(Integer, ForeignKey("achievements.id", ondelete="CASCADE"), nullable=False)
    earned_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user = relationship("User", back_populates="user_achievements")
    achievement = relationship("Achievement")


class UserTopicStats(Base):
    """Per-user per-topic attempt statistics for weak topic detection."""
    __tablename__ = "user_topic_stats"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    topic = Column(String(255), nullable=False, index=True)
    total_attempts = Column(Integer, default=0, nullable=False)
    correct_attempts = Column(Integer, default=0, nullable=False)
    wrong_attempts = Column(Integer, default=0, nullable=False)
    last_updated = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="topic_stats")


class UserProgress(Base):
    """User progress tracking."""
    __tablename__ = "user_progress"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    study_plan_id = Column(Integer, ForeignKey("study_plans.id", ondelete="SET NULL"), nullable=True)
    completed_items = Column(Text, nullable=True)  # JSON array of completed item IDs
    current_streak_days = Column(Integer, default=0)
    last_study_date = Column(DateTime(timezone=True), nullable=True)
    total_points = Column(Integer, default=0)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="user_progress")
    study_plan = relationship("StudyPlan")


# ==================== Collaborative Study Groups ====================

class StudyGroup(Base):
    """Study group for collaborative learning."""
    __tablename__ = "study_groups"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    created_by = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    creator = relationship("User", foreign_keys=[created_by])
    memberships = relationship("GroupMembership", back_populates="group", cascade="all, delete-orphan")
    messages = relationship(
        "GroupMessage", back_populates="group", cascade="all, delete-orphan",
        foreign_keys="GroupMessage.group_id",
    )
    documents = relationship("GroupDocument", back_populates="group", cascade="all, delete-orphan")
    pinned = relationship("PinnedGroupMessage", back_populates="group", uselist=False, cascade="all, delete-orphan")
    invites = relationship("GroupInvite", back_populates="group", cascade="all, delete-orphan")


class GroupMembership(Base):
    """User membership in a study group with role."""
    __tablename__ = "group_memberships"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    group_id = Column(Integer, ForeignKey("study_groups.id", ondelete="CASCADE"), nullable=False)
    role = Column(String(20), nullable=False, default="member")  # admin | member
    joined_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user = relationship("User", back_populates="group_memberships")
    group = relationship("StudyGroup", back_populates="memberships")


class GroupMessage(Base):
    """Message in a group chat. user_id is null for AI messages; sender_type='ai' for AI."""
    __tablename__ = "group_messages"

    id = Column(Integer, primary_key=True, index=True)
    group_id = Column(Integer, ForeignKey("study_groups.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    sender_type = Column(String(20), nullable=False, default="user")  # user | ai
    message = Column(Text, nullable=False)
    message_type = Column(String(20), nullable=False, default="text")  # text | file | ai
    file_path = Column(String(500), nullable=True)  # relative path for file messages
    file_name = Column(String(255), nullable=True)
    message_status = Column(String(20), nullable=False, default="sent")  # sent | delivered
    group_file_id = Column(Integer, ForeignKey("group_documents.id", ondelete="SET NULL"), nullable=True)  # optional attached file for AI context
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    group = relationship("StudyGroup", back_populates="messages", foreign_keys=[group_id])
    user = relationship("User", back_populates="group_messages", foreign_keys=[user_id])
    votes = relationship("MessageVote", back_populates="message", cascade="all, delete-orphan")


class GroupDocument(Base):
    """Document (PDF/image) shared in a group; extracted text for AI context."""
    __tablename__ = "group_documents"

    id = Column(Integer, primary_key=True, index=True)
    group_id = Column(Integer, ForeignKey("study_groups.id", ondelete="CASCADE"), nullable=False)
    file_name = Column(String(255), nullable=False)
    file_path = Column(String(500), nullable=False)  # path under uploads/groups/{group_id}/
    extracted_text = Column(Text, nullable=True)
    uploaded_by = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    group = relationship("StudyGroup", back_populates="documents")
    uploader = relationship("User", foreign_keys=[uploaded_by])


class MessageVote(Base):
    """Upvote on a group message (topic voting)."""
    __tablename__ = "message_votes"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    message_id = Column(Integer, ForeignKey("group_messages.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user = relationship("User", back_populates="message_votes")
    message = relationship("GroupMessage", back_populates="votes")


class PinnedGroupMessage(Base):
    """Single pinned message per group (one row per group)."""
    __tablename__ = "pinned_group_messages"

    id = Column(Integer, primary_key=True, index=True)
    group_id = Column(Integer, ForeignKey("study_groups.id", ondelete="CASCADE"), nullable=False, unique=True)
    message_id = Column(Integer, ForeignKey("group_messages.id", ondelete="CASCADE"), nullable=False)
    pinned_by = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    pinned_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    group = relationship("StudyGroup", back_populates="pinned")
    message = relationship("GroupMessage")
    user = relationship("User", foreign_keys=[pinned_by])


class GroupInvite(Base):
    """Secure invite link for a study group. Token in URL: /groups/invite/{token}."""
    __tablename__ = "group_invites"

    id = Column(Integer, primary_key=True, index=True)
    group_id = Column(Integer, ForeignKey("study_groups.id", ondelete="CASCADE"), nullable=False)
    token = Column(String(64), unique=True, nullable=False, index=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    usage_limit = Column(Integer, nullable=True)  # null = unlimited
    used_count = Column(Integer, nullable=False, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    group = relationship("StudyGroup", back_populates="invites")
